renumbering and documenting

diff --git a/PG-Install-2/pg-install b/PG-Install-2/pg-install
--- a/PG-Install-2/pg-install
+++ b/PG-Install-2/pg-install
@@ -303,11 +303,11 @@ do_set_accounts() {
     local this=do_suss_accounts
 
     # The Account and Group which we use to configure and build PostgreSQL
-    set_final Build_Acct "$(user_exists bin "`cr 10 303 $this`")"
-    set_final Build_Group "$(group_exists bin "`cr 11 304 $this`")"
+    set_final Build_Acct "$(user_exists bin "`cr 10 306 $this`")"
+    set_final Build_Group "$(group_exists bin "`cr 11 307 $this`")"
     # The Account and Group which owns the installed PostgreSQL
-    set_final PG_Acct "$(user_exists postgres "`cr 12 306 $this`")"
-    set_final PG_Group "$(group_exists postgres "`cr 13 307 $this`")"
+    set_final PG_Acct "$(user_exists postgres "`cr 12 309 $this`")"
+    set_final PG_Group "$(group_exists postgres "`cr 13 310 $this`")"
 }
 
 do_set_locations() {
@@ -315,12 +315,12 @@ do_set_locations() {
 
     set_final Build_Grandparent_Dir /usr/local/src
     [ -d "$Build_Grandparent_Dir" ] ||
-        error "`cr 14 315 $this`" expected directory "$Build_Grandparent_Dir"
+        error "`cr 14 318 $this`" expected directory "$Build_Grandparent_Dir"
 
     for d in /usr/local/SW.d /usr/local/SW /usr/local; do
         [ -d "$d" ] && break
     done
-    [ -d "$d" ] || error "`cr 15 320 $this`" "expected PG_Parent_Dir $d"
+    [ -d "$d" ] || error "`cr 15 323 $this`" "expected PG_Parent_Dir $d"
     set_final PG_Parent_Dir "$d"
 }
 
@@ -405,7 +405,7 @@ do_suss_options() {
     declare -g Pattern='unknown'
     # Consider making this a command-line option instead!!
     set_param Build_Shell "$(prog_path_maybe dash sh)" ||
-        error "`cr 17 413 $this`" "can't suss Build_Shell"
+        error "`cr 16 408 $this`" "can't suss Build_Shell"
     set_final Build_Shell;
 
     # record options and save non-option arguments
@@ -421,7 +421,7 @@ do_suss_options() {
     [ -n "${Profile}" ] || ! [ -f "$Profile_Default" ] || \
         set_final Profile "$Profile_Default"
     [ -f "$Profile" ] || \
-        error "`cr 16 326 $this`" expected Profile script "$Profile"
+        error "`cr 17 424 $this`" expected Profile script "$Profile"
     return 0
 }
 
@@ -438,7 +438,7 @@ try_tarball() {
     local this='try_tarball'
     [ $# -gt 0 ] && [ $# -le 2 ] || return 1
     [ -f "$1" ] || return 1
-    [ $# -eq 1 ] || expect_dir "$2" "`cr 18 439 $this`"
+    [ $# -eq 1 ] || expect_dir "$2" "`cr 18 441 $this`"
     local f1=${1##*/} # without the path
     local f2=${f1%.*} # without last extension
     local f           # trial project name
@@ -452,12 +452,12 @@ try_tarball() {
     local v=${f##*-}            # trial version string
     local regexp_pattern='[1-9][0-9]?.[0-9][0-9]?(rc)?'
     [[ "$v" =~ $regexp_pattern ]] ||
-        error "`cr 19 453 $this`" "unknown version pattern in $f"
+        error "`cr 19 455 $this`" "unknown version pattern in $f"
     # We're satisfied, so
     set_final Archive "$(realpath "$1")"
     set_final Version "$v"
     [ $# = 2 ] && set_final Build_Grandparent_Dir "$(realpath "$2")"
-    expect_dir "$Build_Grandparent_Dir" "`cr 20 458 $this`"
+    expect_dir "$Build_Grandparent_Dir" "`cr 20 460 $this`"
     return 0
 }
 
@@ -466,14 +466,14 @@ try_tarball() {
 try_version_git() {
     local this='try_version_git'
     set_final Pattern 'tarball'
-    report -apology "`cr 21 467 $this`" "$Pattern pattern not yet implemented"
+    report -apology "`cr 21 469 $this`" "$Pattern pattern not yet implemented"
     return 1
 }
 
 try_bare_version() {
     local this='try_bare_version'
     set_final Pattern 'version'
-    context_level_report "`cr 22 474 $this`" apology "$Pattern pattern not yet implemented"
+    context_level_report "`cr 22 476 $this`" apology "$Pattern pattern not yet implemented"
     return 1
 }
 
@@ -483,10 +483,10 @@ do_suss_args() {
     local this=do_suss_args
 
     try_tarball "$@" || try_version_git "$@" || try_bare_version "$@" ||
-        error "`cr 23 484 $this`" 'unrecognized install pattern'
+        error "`cr 23 486 $this`" 'unrecognized install pattern'
 
     [ -n "$Version" ] ||
-        error "`cr 24 487 $this`" "Failed to suss a version"
+        error "`cr 24 489 $this`" "Failed to suss a version"
 }
 
 
@@ -526,13 +526,13 @@ do_suss_build_dirs() {
     set_final Project_Name "PostgreSQL-$1"
     set_final Source_Name "${Project_Name,,}" # lower case
     set_final Build_Parent_Dir "$Build_Grandparent_Dir/$Project_Name"
-    ensure_dir "$Build_Parent_Dir" "$Build_Acct" "$Build_Group" "`cr 25 527 $this`"
+    ensure_dir "$Build_Parent_Dir" "$Build_Acct" "$Build_Group" "`cr 25 529 $this`"
     local n=1 d
     while d="$Build_Parent_Dir/Attempt-$n" ; ! empty_dir "$d"; do
         let ++n
     done
     set_final Build_Dir "$d"
-    ensure_dir "$Build_Dir" "$Build_Acct" "$Build_Group" "`cr 26 533 suss_build_dirs`"
+    ensure_dir "$Build_Dir" "$Build_Acct" "$Build_Group" "`cr 26 535 suss_build_dirs`"
 }
 
 # when we know the version, create the PG Dirs
@@ -547,11 +547,11 @@ do_suss_pg_dirs() {
             while old="$PG_Dir-$n"; [ -d "$old" ]; do
                 let ++n
             done
-            report -"install conflict warning" "`cr 27 548 $this`" \
+            report -"install conflict warning" "`cr 27 550 $this`" \
                    mv "$PG_Dir" "$old"
             mv "$PG_Dir" "$old"
         }
-    ensure_dir "$PG_Dir" "$Build_Acct" "$Build_Group" "`cr 28 552 $this`"
+    ensure_dir "$PG_Dir" "$Build_Acct" "$Build_Group" "`cr 28 554 $this`"
     set_final PG_Bin "$PG_Dir/bin"
     set_final PG_Data "$PG_Dir/data"
     set_final PG_Log "$PG_Data/logfile"
@@ -597,23 +597,23 @@ do_prepare_build_dir() {
         (tarball)
         set_param Source_Dir "$Build_Parent_Dir/$Source_Name"
         ensure_dir "$Source_Dir" "$Build_Acct" "$Build_Group" \
-                   "`cr 29 598 $this`"
-        report -command "`cr 30 599 $this`" \
+                   "`cr 29 600 $this`"
+        report -command "`cr 30 601 $this`" \
                chown -R "$Build_Acct:$Build_Group" "$Build_Dir"
         chown -R "$Build_Acct:$Build_Group" "$Build_Parent_Dir"
-        local cxt1="`cr 31 602 $this`"
+        local cxt1="`cr 31 604 $this`"
         su_acct_dir_cmd "$cxt1" "$Build_Acct" "$Build_Parent_Dir" \
                         tar xf "$Archive" ||
             error "$cxt1" "Can't extract $Archive"
         "$Dry_Run" || ! empty_dir "$Source_Dir"  ||
-            expect_dir "$Source_Dir" "`cr 32 607 $this`"
-        su_acct_dir_cmd "`cr 33 608 $this`" "$Build_Acct" "$Build_Parent_Dir" \
+            expect_dir "$Source_Dir" "`cr 32 609 $this`"
+        su_acct_dir_cmd "`cr 33 610 $this`" "$Build_Acct" "$Build_Parent_Dir" \
                         tar cf - "$Source_Name" |
-            su_acct_dir_cmd "`cr 34 610 $this`" "$Build_Acct" "$Build_Dir" \
+            su_acct_dir_cmd "`cr 34 612 $this`" "$Build_Acct" "$Build_Dir" \
                             tar xf - ||
-            error "`cr 35 612 $this`" "Can't copy $Source_Dir to $Build_Dir"
+            error "`cr 35 614 $this`" "Can't copy $Source_Dir to $Build_Dir"
         ;;
-        (*) error "`cr 36 614 $this`" "unimplemented pattern $Pattern" ;;
+        (*) error "`cr 36 616 $this`" "unimplemented pattern $Pattern" ;;
     esac
     return 0
 }
@@ -668,7 +668,7 @@ do_config() {
     set_phase CONFIG
 
     set_param Source_Root "$Build_Dir/$Source_Name"
-    ensure_dir "$Source_Root" "$Build_Acct" "$Build_Group"  "`cr 37 669 $this`" 
+    ensure_dir "$Source_Root" "$Build_Acct" "$Build_Group"  "`cr 37 671 $this`" 
 
     # disable shellcheck wanting quotes around $with_tcl
     # shellcheck disable=SC2206
@@ -682,7 +682,7 @@ do_config() {
 
     $Verbose && report_param_array Config_Options
 
-    local cxt="`cr 38 683 $this`"
+    local cxt="`cr 38 685 $this`"
     su_acct_dir_cmd_log "$cxt" "$Build_Acct" "$Source_Root" ./configure "${Config_Options[*]}" ||
         log_error "$cxt" "./configure -> $?"
 }
@@ -694,7 +694,7 @@ do_build() {
 
     set_phase BUILD
 
-    local cxt="`cr 39 695 $this`"
+    local cxt="`cr 39 697 $this`"
     su_acct_dir_cmd_log "$cxt" "$Build_Acct" "$Source_Root" make ||
         log_error "$cxt" "make -> $?"
 }
@@ -704,7 +704,7 @@ do_install() {
 
     set_phase INSTALL
 
-    local cxt="`cr 40 705 $this`"
+    local cxt="`cr 40 707 $this`"
     su_acct_dir_cmd_log "$cxt" "$Build_Acct" "$Source_Root" make install ||
         log_error "$cxt" "make install -> $?"
 }
@@ -715,17 +715,17 @@ do_build_install_contribs() {
     local d this=do_build_install_contribs
 
     set_final Contrib_Dir "$Source_Root/contrib"
-    expect_dir "$Contrib_Dir" "`cr 41 716 $this`"
+    expect_dir "$Contrib_Dir" "`cr 41 718 $this`"
 
     for d in xml2 intarray citext hstore
     do
         set_phase $d-BUILD
-        local cxt1="`cr 42 721 $this`"
+        local cxt1="`cr 42 723 $this`"
         su_acct_dir_cmd_log "$cxt1" "$Build_Acct" "$Contrib_Dir" make ||
             error "$cxt1" "make -> $?"
 
         set_phase $d-INSTALL
-        local cxt2="`cr 43 726 $this`"
+        local cxt2="`cr 43 728 $this`"
         su_acct_dir_cmd_log "$cxt2" "$Build_Acct" "$Contrib_Dir" make install ||
             error "$cxt2" "make install -> $?"
     done
@@ -771,15 +771,15 @@ do_init_pg() {
 
     set_phase POSTGRES
 
-    ensure_dir "$PG_Data" "$PG_Acct" "$PG_Group" "`cr 44 762 $this`"
-    try "`cr 45 763 $this`" empty_dir "$PG_Data"
-    try "`cr 46 764 $this`" chmod 700 "$PG_Data"
+    ensure_dir "$PG_Data" "$PG_Acct" "$PG_Group" "`cr 44 774 $this`"
+    try "`cr 45 775 $this`" empty_dir "$PG_Data"
+    try "`cr 46 776 $this`" chmod 700 "$PG_Data"
     # Change whole install area ownership from Build_Acct to PG_Acct
-    try "`cr 47 766 $this`" chown -R "$PG_Acct:$PG_Group" "$PG_Dir"
-    pg_data_cmd "`cr 48 767 $this`" initdb ||
-        error "`cr 49 768 $this`" "initdb -> $?"
+    try "`cr 47 778 $this`" chown -R "$PG_Acct:$PG_Group" "$PG_Dir"
+    pg_data_cmd "`cr 48 779 $this`" initdb ||
+        error "`cr 49 780 $this`" "initdb -> $?"
     # we should take care of this: !!
-    report "`cr 50 770 $this`" "-remember to" \
+    report "`cr 50 782 $this`" "-remember to" \
            "ln -s XFiles directory to $PG_Data"
 }
 
@@ -791,8 +791,8 @@ do_start_pg() {
     # and do something appropriate if there is!!
 
     # start the PostgreSQL server
-    pg_data_cmd "`cr 51 782 $this`" "pg_ctl -l $PG_Log" start ||
-        error "`cr 52 783 $this`" "starting server -> $?"
+    pg_data_cmd "`cr 51 794 $this`" "pg_ctl -l $PG_Log" start ||
+        error "`cr 52 795 $this`" "starting server -> $?"
     sleep 5	# seems to need a moment to get ready
 }
 
@@ -805,8 +805,8 @@ add_pg_langs() {
     for lang; do
         # try $PG_Bin/createlang "$lang" template1
         printf -- "create trusted procedural language '%s';\n" "$lang" |
-            pg_bin_cmd "`cr 53 797 $this`" psql -a template1 || {
-            report "`cr 54 798 $this`" "createlang $lang -> $?"
+            pg_bin_cmd "`cr 53 808 $this`" psql -a template1 || {
+            report "`cr 54 809 $this`" "createlang $lang -> $?"
             let ++PG_Problem_Count
         }
     done
@@ -817,8 +817,8 @@ add_pg_langs() {
 create_pg_databases() {
     local db this=do_create_databases
     for db; do
-        pg_bin_cmd "`cr 55 809 $this`" createdb "$db" || {
-            report "`cr 56 810 $this`" "createdb $db -> $?"
+        pg_bin_cmd "`cr 55 820 $this`" createdb "$db" || {
+            report "`cr 56 821 $this`" "createdb $db -> $?"
             let ++PG_Problem_Count
         }
     done
@@ -827,10 +827,10 @@ create_pg_databases() {
 # backup $PG_Conf to $PG_Conf_Orig 
 backup_pg_conf_file() {
     local this=backup_pg_conf_file
-    pg_cmd "`cr 57 818 $this`" mv "$PG_Conf" "$PG_Conf_Orig" ||
-        report "`cr 58 819 $this`" "mv ${PG_Conf##*/} -> $?"
-    pg_cmd "`cr 59 820 $this`" cp "$PG_Conf_Orig" "$PG_Conf" ||
-        report "`cr 60 821 $this`" "cp ${PG_Conf##*/} -> $?"
+    pg_cmd "`cr 57 830 $this`" mv "$PG_Conf" "$PG_Conf_Orig" ||
+        report "`cr 58 831 $this`" "mv ${PG_Conf##*/} -> $?"
+    pg_cmd "`cr 59 832 $this`" cp "$PG_Conf_Orig" "$PG_Conf" ||
+        report "`cr 60 833 $this`" "cp ${PG_Conf##*/} -> $?"
 }
 
 # create_pg_superusers USER_ACCOUNT...
@@ -838,8 +838,8 @@ create_pg_superusers() {
     local user this=create_pg_superusers
     for user; do
         { user_exists "$user" &&
-              pg_bin_cmd "`cr 62 837 $this`" createuser --superuser "$user"
-        } || report "`cr 63 838 $this`" "createuser $user -> $?"
+              pg_bin_cmd "`cr 61 841 $this`" createuser --superuser "$user"
+        } || report "`cr 62 842 $this`" "createuser $user -> $?"
     done
 }
 
@@ -858,7 +858,7 @@ edit_pg_conf() {
     sed "/$setting *=/h;s/^#*//;s/$from/$to/;x" \
         "$PG_Conf" >> "$PG_Conf.$setting"
     [ 2 -eq $(grep -c "\\<$setting\\>") ] || {
-        report -warning "`cr 56 810 $this`" "$conf2 count != 2"
+        report -warning "`cr 63 861 $this`" "$conf2 count != 2"
         let ++PG_Problem_Count
         return 1
     }
@@ -875,7 +875,7 @@ do_pg_postinstall() {
     ! [ -v PG_Databases ] || create_pg_databases "${PG_Databases[@]}"
 
     ! [ -v PG_Wicci_XFiles ] || ! [ -d "$PG_Wicci_XFiles"  ] ||
-        pg_cmd "`cr 1 1 $this`" \
+        pg_cmd "`cr 64 878 $this`" \
                             ln -s "$PG_Wicci_XFiles" "$PG_Data/XFiles"
 
     # Backup and then edit $PG_Conf
@@ -906,7 +906,7 @@ do_suss_options "$@"
 set -- "${Pgm_Args[@]}"      # options now gone from "$@"
 
 # Uses whoami
-test root = "`whoami`" || error "`cr 64 855 $Pgm_Name`" "Must run as root!"
+test root = "`whoami`" || error "`cr 65 909 $Pgm_Name`" "Must run as root!"
 
 # Figure out the Version from the Pattern!
 do_suss_args "$@"               # non-option arguments
@@ -919,7 +919,7 @@ if [ -f "${Profile}" ]; then
     report '' source "${Profile}" 
     source "${Profile}"
 else
-    report -warning "`cr 1 1`" "No Configuration Profile $Profile"
+    report -warning "`cr 66 922`" "No Configuration Profile $Profile"
 fi
 
 # Where's everything going to go?
