fixing with Bill

diff --git a/PG-Install-2/pg-install b/PG-Install-2/pg-install
--- a/PG-Install-2/pg-install
+++ b/PG-Install-2/pg-install
@@ -259,6 +259,7 @@ report_params() {
 }
 
 # set_param_silently global_parameter [value]
+# should we warn if the parameter already had a value??
 set_param_silently() {
     { [ $# -ge 1 ] && [ $# -le 2 ]; } ||
         error "set_param given $# arguments"
@@ -279,7 +280,14 @@ set_param() {
 }
 
 # set_final global_parameter [value]
+# sets the global parameter as a readonly value
+# any later attempt to reset that parameter will be warned or ignored
 set_final() {
+    local -n v="$1"             # alias v to the parameter name
+    if [ -n "${v:-}" ]; then
+        # maybe warn of an attempt to reset the parameter??
+        return 0
+    fi
     set_param "$@"
     declare -gr "$1"            # declare as global readonly
 }
@@ -288,26 +296,38 @@ set_final() {
 
 # Uses grep
 # Assumes FILE is Posix /etc/passwd or /etc/group
-# user_group_exists NAME 'user|group' FILE [CONTEXT]
-user_group_exists() {
-    local context="${4:-}"
+# user_or_group_exists NAME 'user|group' FILE [CONTEXT]
+user_or_group_exists() {
+    local this='user_or_group_exists'
+    local context="${4:-"`cr 10 302 $this`"}"
     grep -qs "^$1:" "$3" || error "$context" "No $2 $1 in $3"
     printf -- '%s' "$1"            # return value
 }
 # user_exists USER-NAME [CONTEXT]
-user_exists() { user_group_exists "$1" 'user' '/etc/passwd' "${2:-}"; }
+user_exists() {
+    local this='user_exists'
+    local context="${4:-"`cr 11 309 $this`"}"
+    if type -P id >/dev/null; then
+        id "$1" >/dev/null || error "$context" "No user $1"
+        printf -- '%s' "$1"            # return value
+    else
+        user_or_group_exists "$1" 'user' '/etc/passwd' "${2:-}"
+    fi
+}
 # group_exists GROUP-NAME [CONTEXT]
-group_exists() { user_group_exists "$1" 'group' '/etc/group' "${2:-}"; }
+group_exists() {
+    user_or_group_exists "$1" 'group' '/etc/group' "${2:-}"
+}
 
 do_set_accounts() {
     local this=do_suss_accounts
 
     # The Account and Group which we use to configure and build PostgreSQL
-    set_final Build_Acct "$(user_exists bin "`cr 10 306 $this`")"
-    set_final Build_Group "$(group_exists bin "`cr 11 307 $this`")"
+    set_final Build_Acct "$(user_exists bin "`cr 12 326 $this`")"
+    set_final Build_Group "$(group_exists bin "`cr 13 327 $this`")"
     # The Account and Group which owns the installed PostgreSQL
-    set_final PG_Acct "$(user_exists postgres "`cr 12 309 $this`")"
-    set_final PG_Group "$(group_exists postgres "`cr 13 310 $this`")"
+    set_final PG_Acct "$(user_exists postgres "`cr 14 329 $this`")"
+    set_final PG_Group "$(group_exists postgres "`cr 15 330 $this`")"
 }
 
 do_set_locations() {
@@ -315,12 +335,12 @@ do_set_locations() {
 
     set_final Build_Grandparent_Dir /usr/local/src
     [ -d "$Build_Grandparent_Dir" ] ||
-        error "`cr 14 318 $this`" expected directory "$Build_Grandparent_Dir"
+        error "`cr 16 338 $this`" expected directory "$Build_Grandparent_Dir"
 
     for d in /usr/local/SW.d /usr/local/SW /usr/local; do
         [ -d "$d" ] && break
     done
-    [ -d "$d" ] || error "`cr 15 323 $this`" "expected PG_Parent_Dir $d"
+    [ -d "$d" ] || error "`cr 17 343 $this`" "expected PG_Parent_Dir $d"
     set_final PG_Parent_Dir "$d"
 }
 
@@ -366,8 +386,8 @@ option_maybe() {
             # if reported will have wrong value :-(
             # so don't use set_final -- hang head in shame!!!
             declare -g Verbose='true' ;;
-        ("${key}"=*) set_final "$param" "$val" ;; # value parameter
-        ("${key}") set_final "$param" true ;;        # boolean parameter
+        ("${key}"=*) set_param "$param" "$val" ;; # value parameter
+        ("${key}") set_param "$param" true ;;        # boolean parameter
         (*) >&2 echo "option_arg: impossible option $option"
             exit 1 ;;
     esac
@@ -402,10 +422,10 @@ do_suss_options() {
     local arg
     index_options
     set_option_defaults
-    declare -g Pattern='unknown'
+    declare -g Pattern=''
     # Consider making this a command-line option instead!!
     set_param Build_Shell "$(prog_path_maybe dash sh)" ||
-        error "`cr 16 408 $this`" "can't suss Build_Shell"
+        error "`cr 18 428 $this`" "can't suss Build_Shell"
     set_final Build_Shell;
 
     # record options and save non-option arguments
@@ -421,7 +441,7 @@ do_suss_options() {
     [ -n "${Profile}" ] || ! [ -f "$Profile_Default" ] || \
         set_final Profile "$Profile_Default"
     [ -f "$Profile" ] || \
-        error "`cr 17 424 $this`" expected Profile script "$Profile"
+        error "`cr 19 444 $this`" expected Profile script "$Profile"
     return 0
 }
 
@@ -438,7 +458,7 @@ try_tarball() {
     local this='try_tarball'
     [ $# -gt 0 ] && [ $# -le 2 ] || return 1
     [ -f "$1" ] || return 1
-    [ $# -eq 1 ] || expect_dir "$2" "`cr 18 441 $this`"
+    [ $# -eq 1 ] || expect_dir "$2" "`cr 20 461 $this`"
     local f1=${1##*/} # without the path
     local f2=${f1%.*} # without last extension
     local f           # trial project name
@@ -452,12 +472,12 @@ try_tarball() {
     local v=${f##*-}            # trial version string
     local regexp_pattern='[1-9][0-9]?.[0-9][0-9]?(rc)?'
     [[ "$v" =~ $regexp_pattern ]] ||
-        error "`cr 19 455 $this`" "unknown version pattern in $f"
+        error "`cr 21 475 $this`" "unknown version pattern in $f"
     # We're satisfied, so
     set_final Archive "$(realpath "$1")"
     set_final Version "$v"
     [ $# = 2 ] && set_final Build_Grandparent_Dir "$(realpath "$2")"
-    expect_dir "$Build_Grandparent_Dir" "`cr 20 460 $this`"
+    expect_dir "$Build_Grandparent_Dir" "`cr 22 480 $this`"
     return 0
 }
 
@@ -466,14 +486,14 @@ try_tarball() {
 try_version_git() {
     local this='try_version_git'
     set_final Pattern 'tarball'
-    report -apology "`cr 21 469 $this`" "$Pattern pattern not yet implemented"
+    report -apology "`cr 23 489 $this`" "$Pattern pattern not yet implemented"
     return 1
 }
 
 try_bare_version() {
     local this='try_bare_version'
     set_final Pattern 'version'
-    context_level_report "`cr 22 476 $this`" apology "$Pattern pattern not yet implemented"
+    context_level_report "`cr 24 496 $this`" apology "$Pattern pattern not yet implemented"
     return 1
 }
 
@@ -483,10 +503,10 @@ do_suss_args() {
     local this=do_suss_args
 
     try_tarball "$@" || try_version_git "$@" || try_bare_version "$@" ||
-        error "`cr 23 486 $this`" 'unrecognized install pattern'
+        error "`cr 25 506 $this`" 'unrecognized install pattern'
 
     [ -n "$Version" ] ||
-        error "`cr 24 489 $this`" "Failed to suss a version"
+        error "`cr 26 509 $this`" "Failed to suss a version"
 }
 
 
@@ -513,7 +533,7 @@ ensure_dir() {
         [ -e "$dir" ] &&          # whoops, something else there!
             error "$cxt" "Expected directory $dir"
         report -command "$cxt" mkdir -p "$dir"
-        mkdir "$dir"
+        mkdir -p "$dir"
         report -command "$cxt" chown "$acct:$group" "$dir"
         chown "$acct:$group" "$dir"
     }
@@ -526,13 +546,13 @@ do_suss_build_dirs() {
     set_final Project_Name "PostgreSQL-$1"
     set_final Source_Name "${Project_Name,,}" # lower case
     set_final Build_Parent_Dir "$Build_Grandparent_Dir/$Project_Name"
-    ensure_dir "$Build_Parent_Dir" "$Build_Acct" "$Build_Group" "`cr 25 529 $this`"
+    ensure_dir "$Build_Parent_Dir" "$Build_Acct" "$Build_Group" "`cr 27 549 $this`"
     local n=1 d
     while d="$Build_Parent_Dir/Attempt-$n" ; ! empty_dir "$d"; do
         let ++n
     done
     set_final Build_Dir "$d"
-    ensure_dir "$Build_Dir" "$Build_Acct" "$Build_Group" "`cr 26 535 suss_build_dirs`"
+    ensure_dir "$Build_Dir" "$Build_Acct" "$Build_Group" "`cr 28 555 suss_build_dirs`"
 }
 
 # when we know the version, create the PG Dirs
@@ -547,11 +567,11 @@ do_suss_pg_dirs() {
             while old="$PG_Dir-$n"; [ -d "$old" ]; do
                 let ++n
             done
-            report -"install conflict warning" "`cr 27 550 $this`" \
+            report -"install conflict warning" "`cr 29 570 $this`" \
                    mv "$PG_Dir" "$old"
             mv "$PG_Dir" "$old"
         }
-    ensure_dir "$PG_Dir" "$Build_Acct" "$Build_Group" "`cr 28 554 $this`"
+    ensure_dir "$PG_Dir" "$Build_Acct" "$Build_Group" "`cr 30 574 $this`"
     set_final PG_Bin "$PG_Dir/bin"
     set_final PG_Data "$PG_Dir/data"
     set_final PG_Log "$PG_Data/logfile"
@@ -597,23 +617,23 @@ do_prepare_build_dir() {
         (tarball)
         set_param Source_Dir "$Build_Parent_Dir/$Source_Name"
         ensure_dir "$Source_Dir" "$Build_Acct" "$Build_Group" \
-                   "`cr 29 600 $this`"
-        report -command "`cr 30 601 $this`" \
+                   "`cr 31 620 $this`"
+        report -command "`cr 32 621 $this`" \
                chown -R "$Build_Acct:$Build_Group" "$Build_Dir"
         chown -R "$Build_Acct:$Build_Group" "$Build_Parent_Dir"
-        local cxt1="`cr 31 604 $this`"
+        local cxt1="`cr 33 624 $this`"
         su_acct_dir_cmd "$cxt1" "$Build_Acct" "$Build_Parent_Dir" \
                         tar xf "$Archive" ||
             error "$cxt1" "Can't extract $Archive"
         "$Dry_Run" || ! empty_dir "$Source_Dir"  ||
-            expect_dir "$Source_Dir" "`cr 32 609 $this`"
-        su_acct_dir_cmd "`cr 33 610 $this`" "$Build_Acct" "$Build_Parent_Dir" \
+            expect_dir "$Source_Dir" "`cr 34 629 $this`"
+        su_acct_dir_cmd "`cr 35 630 $this`" "$Build_Acct" "$Build_Parent_Dir" \
                         tar cf - "$Source_Name" |
-            su_acct_dir_cmd "`cr 34 612 $this`" "$Build_Acct" "$Build_Dir" \
+            su_acct_dir_cmd "`cr 36 632 $this`" "$Build_Acct" "$Build_Dir" \
                             tar xf - ||
-            error "`cr 35 614 $this`" "Can't copy $Source_Dir to $Build_Dir"
+            error "`cr 37 634 $this`" "Can't copy $Source_Dir to $Build_Dir"
         ;;
-        (*) error "`cr 36 616 $this`" "unimplemented pattern $Pattern" ;;
+        (*) error "`cr 38 636 $this`" "unimplemented pattern $Pattern" ;;
     esac
     return 0
 }
@@ -656,7 +676,7 @@ log_example() {
 # log_error CONTEXT REPORT...
 log_error() {
     local code=$(cs_code_maybe "$1")
-    report -error "@"
+    report -error "$@"
     exit "$code"
 }
 
@@ -668,7 +688,7 @@ do_config() {
     set_phase CONFIG
 
     set_param Source_Root "$Build_Dir/$Source_Name"
-    ensure_dir "$Source_Root" "$Build_Acct" "$Build_Group"  "`cr 37 671 $this`" 
+    ensure_dir "$Source_Root" "$Build_Acct" "$Build_Group"  "`cr 39 691 $this`" 
 
     # disable shellcheck wanting quotes around $with_tcl
     # shellcheck disable=SC2206
@@ -682,7 +702,7 @@ do_config() {
 
     $Verbose && report_param_array Config_Options
 
-    local cxt="`cr 38 685 $this`"
+    local cxt="`cr 40 705 $this`"
     su_acct_dir_cmd_log "$cxt" "$Build_Acct" "$Source_Root" ./configure "${Config_Options[*]}" ||
         log_error "$cxt" "./configure -> $?"
 }
@@ -694,7 +714,7 @@ do_build() {
 
     set_phase BUILD
 
-    local cxt="`cr 39 697 $this`"
+    local cxt="`cr 41 717 $this`"
     su_acct_dir_cmd_log "$cxt" "$Build_Acct" "$Source_Root" make ||
         log_error "$cxt" "make -> $?"
 }
@@ -704,7 +724,7 @@ do_install() {
 
     set_phase INSTALL
 
-    local cxt="`cr 40 707 $this`"
+    local cxt="`cr 42 727 $this`"
     su_acct_dir_cmd_log "$cxt" "$Build_Acct" "$Source_Root" make install ||
         log_error "$cxt" "make install -> $?"
 }
@@ -715,17 +735,17 @@ do_build_install_contribs() {
     local d this=do_build_install_contribs
 
     set_final Contrib_Dir "$Source_Root/contrib"
-    expect_dir "$Contrib_Dir" "`cr 41 718 $this`"
+    expect_dir "$Contrib_Dir" "`cr 43 738 $this`"
 
     for d in xml2 intarray citext hstore
     do
         set_phase $d-BUILD
-        local cxt1="`cr 42 723 $this`"
+        local cxt1="`cr 44 743 $this`"
         su_acct_dir_cmd_log "$cxt1" "$Build_Acct" "$Contrib_Dir" make ||
             error "$cxt1" "make -> $?"
 
         set_phase $d-INSTALL
-        local cxt2="`cr 43 728 $this`"
+        local cxt2="`cr 45 748 $this`"
         su_acct_dir_cmd_log "$cxt2" "$Build_Acct" "$Contrib_Dir" make install ||
             error "$cxt2" "make install -> $?"
     done
@@ -771,15 +791,15 @@ do_init_pg() {
 
     set_phase POSTGRES
 
-    ensure_dir "$PG_Data" "$PG_Acct" "$PG_Group" "`cr 44 774 $this`"
-    try "`cr 45 775 $this`" empty_dir "$PG_Data"
-    try "`cr 46 776 $this`" chmod 700 "$PG_Data"
+    ensure_dir "$PG_Data" "$PG_Acct" "$PG_Group" "`cr 46 794 $this`"
+    try "`cr 47 795 $this`" empty_dir "$PG_Data"
+    try "`cr 48 796 $this`" chmod 700 "$PG_Data"
     # Change whole install area ownership from Build_Acct to PG_Acct
-    try "`cr 47 778 $this`" chown -R "$PG_Acct:$PG_Group" "$PG_Dir"
-    pg_data_cmd "`cr 48 779 $this`" initdb ||
-        error "`cr 49 780 $this`" "initdb -> $?"
+    try "`cr 49 798 $this`" chown -R "$PG_Acct:$PG_Group" "$PG_Dir"
+    pg_data_cmd "`cr 50 799 $this`" initdb ||
+        error "`cr 51 800 $this`" "initdb -> $?"
     # we should take care of this: !!
-    report "`cr 50 782 $this`" "-remember to" \
+    report "`cr 52 802 $this`" "-remember to" \
            "ln -s XFiles directory to $PG_Data"
 }
 
@@ -791,8 +811,8 @@ do_start_pg() {
     # and do something appropriate if there is!!
 
     # start the PostgreSQL server
-    pg_data_cmd "`cr 51 794 $this`" "pg_ctl -l $PG_Log" start ||
-        error "`cr 52 795 $this`" "starting server -> $?"
+    pg_data_cmd "`cr 53 814 $this`" "pg_ctl -l $PG_Log" start ||
+        error "`cr 54 815 $this`" "starting server -> $?"
     sleep 5	# seems to need a moment to get ready
 }
 
@@ -805,8 +825,8 @@ add_pg_langs() {
     for lang; do
         # try $PG_Bin/createlang "$lang" template1
         printf -- "create trusted procedural language '%s';\n" "$lang" |
-            pg_bin_cmd "`cr 53 808 $this`" psql -a template1 || {
-            report "`cr 54 809 $this`" "createlang $lang -> $?"
+            pg_bin_cmd "`cr 55 828 $this`" psql -a template1 || {
+            report "`cr 56 829 $this`" "createlang $lang -> $?"
             let ++PG_Problem_Count
         }
     done
@@ -817,8 +837,8 @@ add_pg_langs() {
 create_pg_databases() {
     local db this=do_create_databases
     for db; do
-        pg_bin_cmd "`cr 55 820 $this`" createdb "$db" || {
-            report "`cr 56 821 $this`" "createdb $db -> $?"
+        pg_bin_cmd "`cr 57 840 $this`" createdb "$db" || {
+            report "`cr 58 841 $this`" "createdb $db -> $?"
             let ++PG_Problem_Count
         }
     done
@@ -827,10 +847,10 @@ create_pg_databases() {
 # backup $PG_Conf to $PG_Conf_Orig 
 backup_pg_conf_file() {
     local this=backup_pg_conf_file
-    pg_cmd "`cr 57 830 $this`" mv "$PG_Conf" "$PG_Conf_Orig" ||
-        report "`cr 58 831 $this`" "mv ${PG_Conf##*/} -> $?"
-    pg_cmd "`cr 59 832 $this`" cp "$PG_Conf_Orig" "$PG_Conf" ||
-        report "`cr 60 833 $this`" "cp ${PG_Conf##*/} -> $?"
+    pg_cmd "`cr 59 850 $this`" mv "$PG_Conf" "$PG_Conf_Orig" ||
+        report "`cr 60 851 $this`" "mv ${PG_Conf##*/} -> $?"
+    pg_cmd "`cr 61 852 $this`" cp "$PG_Conf_Orig" "$PG_Conf" ||
+        report "`cr 62 853 $this`" "cp ${PG_Conf##*/} -> $?"
 }
 
 # create_pg_superusers USER_ACCOUNT...
@@ -838,8 +858,8 @@ create_pg_superusers() {
     local user this=create_pg_superusers
     for user; do
         { user_exists "$user" &&
-              pg_bin_cmd "`cr 61 841 $this`" createuser --superuser "$user"
-        } || report "`cr 62 842 $this`" "createuser $user -> $?"
+              pg_bin_cmd "`cr 63 861 $this`" createuser --superuser "$user"
+        } || report "`cr 64 862 $this`" "createuser $user -> $?"
     done
 }
 
@@ -858,7 +878,7 @@ edit_pg_conf() {
     sed "/$setting *=/h;s/^#*//;s/$from/$to/;x" \
         "$PG_Conf" >> "$PG_Conf.$setting"
     [ 2 -eq $(grep -c "\\<$setting\\>") ] || {
-        report -warning "`cr 63 861 $this`" "$conf2 count != 2"
+        report -warning "`cr 65 881 $this`" "$conf2 count != 2"
         let ++PG_Problem_Count
         return 1
     }
@@ -875,7 +895,7 @@ do_pg_postinstall() {
     ! [ -v PG_Databases ] || create_pg_databases "${PG_Databases[@]}"
 
     ! [ -v PG_Wicci_XFiles ] || ! [ -d "$PG_Wicci_XFiles"  ] ||
-        pg_cmd "`cr 64 878 $this`" \
+        pg_cmd "`cr 66 898 $this`" \
                             ln -s "$PG_Wicci_XFiles" "$PG_Data/XFiles"
 
     # Backup and then edit $PG_Conf
@@ -896,21 +916,13 @@ do_pg_postinstall() {
 # You can find all of their definitions by running
 # grep -n '^do_.*()' pg-install
 
-# set parameters not requiring script arguments, i.e. "$@"
-do_set_accounts
-do_set_locations
-
 # Store script OPTIONS as parameter values
 # put regular options into global array Pgm_Args
 do_suss_options "$@"
 set -- "${Pgm_Args[@]}"      # options now gone from "$@"
 
-# Uses whoami
-test root = "`whoami`" || error "`cr 65 909 $Pgm_Name`" "Must run as root!"
-
-# Figure out the Version from the Pattern!
-do_suss_args "$@"               # non-option arguments
-
+# Options for the configure script, doesn't have to be pre-declared
+# document its existence because likely extended by the Profile
 declare -ga Config_Options
 
 # Strategic place to source the Profile as it can
@@ -919,8 +931,18 @@ if [ -f "${Profile}" ]; then
     report '' source "${Profile}" 
     source "${Profile}"
 else
-    report -warning "`cr 66 922`" "No Configuration Profile $Profile"
+    report -warning "`cr 67 934`" "No Configuration Profile $Profile"
 fi
+
+# set parameters not requiring script arguments, i.e. "$@"
+do_set_accounts
+do_set_locations
+
+# Uses whoami
+test root = "`whoami`" || error "`cr 68 942 $Pgm_Name`" "Must run as root!"
+
+# Figure out the Version from the Pattern!
+do_suss_args "$@"               # non-option arguments
 
 # Where's everything going to go?
 do_suss_build_dirs "$Version"
