fixed up su and contexts

diff --git a/PG-Install-2/pg-install b/PG-Install-2/pg-install
--- a/PG-Install-2/pg-install
+++ b/PG-Install-2/pg-install
@@ -208,7 +208,7 @@ do_suss_pg_dirs() {
             report "`cr 18 208 $this`" 'install conflict' mv "$PG_Dir" "$old"
             mv "$PG_Dir" "$old"
         }
-    ensure_dir "$PG_Dir" "$Build_Acct" "$Build_Group" 1! suss_install_dir
+    ensure_dir "$PG_Dir" "$Build_Acct" "$Build_Group" "`cr 19 211 $this`"
     declare -gr PG_Bin="$PG_Dir/bin"
     declare -gr PG_Data="$PG_Dir/data"
     declare -gr PG_Log="$PG_Data/logfile"
@@ -258,9 +258,9 @@ declare -ra Arg_Pattern_Explanations=(
 
 # These three arrays should have the same number of elements
 [ "${#Patterns[@]}" =  "${#Arg_Patterns[@]}" ] ||
-    error "`cr 19 261 "$Pgm_Name"`" "#Patterns != #Arg_Patterns"
+    error "`cr 20 261 "$Pgm_Name"`" "#Patterns != #Arg_Patterns"
 [ "${#Patterns[@]}" =  "${#Arg_Pattern_Explanations[@]}" ] ||
-    error "`cr 20 263 "$Pgm_Name"`" "#Patterns != #Arg_Pattern_Explanations"
+    error "`cr 21 263 "$Pgm_Name"`" "#Patterns != #Arg_Pattern_Explanations"
 
 give_full_help() {
     local i
@@ -274,7 +274,7 @@ give_full_help() {
     printf '\t%s\n' 'Unmet dependencies should cause it to abort.'
     printf '\t%s\n' 'Logs and work done so far left for you to examine.'
     printf '\t%s\n' 'Too many assumptions for any hard guarantees!'
-    printf '\t%s\n' 'May behave arbitrary badly in unfamiliar environment.'
+    printf '\t%s\n' 'May behave arbitrarily badly in unfamiliar environment.'
 }
 
 # ** Process Command Line Options
@@ -297,9 +297,10 @@ do_suss_options() {
     declare -g Verbose='false'
     declare -g Pattern='unknown'
     # Consider making this a command-line option instead!!
-    declare -gr Build_Shell;
+    declare -g Build_Shell;
     Build_Shell="$(try_find_prog_path dash sh)" ||
-        error "`cr 21 302 $this`" "can't suss Build_Shell"
+        error "`cr 22 302 $this`" "can't suss Build_Shell"
+    declare -gr Build_Shell;
 
     Sussed_Globals+=(Pattern Give_Help Dry_Run Build_Shell)
 
@@ -321,16 +322,18 @@ report_param() {
     printf -- '%s = %s\n' "$1" "$v"
 }
 
+report_param_array() {
+    local -n a="$1"
+    local i
+    printf -- 'Contents of array %s:\n' "$1"
+    for i in ${!a[@]}; do
+        printf -- '%s[%d]: %s\n' "$1" "$i" "${a[$i]}"
+    done
+}
+
 report_params() {
     local p; for p; do report_param "$p"; done
 }
-
-$Verbose && {
-    report_params "${Initial_Globals[@]}"
-    report "`cr 22 330`" 'Arguments' "${Pgm_Args[*]}"
-}
-
-# Sussed_Globals can be reported later
 
 # ** Determine Argument Patterns and Finalize Globals
 
@@ -341,7 +344,7 @@ try_tarball() {
     local this='try_tarball'
     [ $# -gt 0 ] && [ $# -le 2 ] || return 1
     [ -f "$1" ] || return 1
-    [ $# -eq 1 ] || expect_dir "$2" "`cr 23 344 $this`"
+    [ $# -eq 1 ] || expect_dir "$2" "`cr 23 346 $this`"
     local f1=${1##*/} # without the path
     local f2=${f1%.*} # without last extension
     local f           # trial project name
@@ -355,14 +358,14 @@ try_tarball() {
     local v=${f##*-}            # trial version string
     local regexp_pattern='[1-9][0-9]?.[0-9][0-9]?(rc)?'
     [[ "$v" =~ $regexp_pattern ]] ||
-        error "`cr 24 358 $this`" "unknown version pattern in $f"
+        error "`cr 24 360 $this`" "unknown version pattern in $f"
     # We're satisfied, so
     Archive=$(realpath "$1")
     Sussed_Globals+=(Archive)
     Version="$v"
     Sussed_Globals+=(Version)
     [ $# = 2 ] && Build_Grandparent_Dir="$(realpath "$2")"
-    expect_dir "$Build_Grandparent_Dir" "`cr 25 365 $this`"
+    expect_dir "$Build_Grandparent_Dir" "`cr 25 367 $this`"
     return 0
 }
 
@@ -371,14 +374,14 @@ try_tarball() {
 try_version_git() {
     local this='try_version_git'
     Pattern='tarball'
-    context_level_report "`cr 26 374 $this`" apology "$Pattern pattern not yet implemented"
+    context_level_report "`cr 26 376 $this`" apology "$Pattern pattern not yet implemented"
     return 1
 }
 
 try_bare_version() {
     local this='try_bare_version'
     Pattern='version'
-    context_level_report "`cr 27 381 $this`" apology "$Pattern pattern not yet implemented"
+    context_level_report "`cr 27 383 $this`" apology "$Pattern pattern not yet implemented"
     return 1
 }
 
@@ -388,10 +391,10 @@ do_suss_args() {
     local this=do_suss_args
 
     try_tarball "$@" || try_version_git "$@" || try_bare_version "$@" ||
-        error "`cr 28 391 $this`" 'unrecognized install pattern'
+        error "`cr 28 393 $this`" 'unrecognized install pattern'
 
     [ -n "$Version" ] ||
-        error "`cr 29 394 $this`" "Failed to suss a version"
+        error "`cr 29 396 $this`" "Failed to suss a version"
     Sussed_Globals+=(Version)
 }
 
@@ -407,13 +410,12 @@ do_try_find_tcl() {
         with_tcl="--with-tclconfig=${tcl%/*}"
     else
         with_tcl=''
-        report -warning "`cr 30 410 $this`" "Can't find tcl, will proceed without it!!"
+        report -warning "`cr 30 412 $this`" "Can't find tcl, will proceed without it!!"
     fi
 }
 
 # ** Prepare, Configure, Build, Install
 
-$Verbose && report_params "${Sussed_Globals[@]}"
 # set -xv
 
 # *** Prepare Build Directory With Fresh Source
@@ -426,15 +428,15 @@ do_prepare_build_dir() {
         (tarball)
         declare -g Source_Dir="$Build_Parent_Dir/$Source_Name"
         [ -d "$Source_Dir" ] || {
-            ensure_dir "$Build_Parent_Dir" "$Build_Acct" "$Build_Group" "`cr 31 429 $this`"
+            ensure_dir "$Build_Parent_Dir" "$Build_Acct" "$Build_Group" "`cr 31 430 $this`"
             tar xf - -C "$Build_Parent_Dir" "$Archive" ||
-                error "`cr 32 431 $this`" "Can't extract $Archive"
-            expect_dir "$Source_Dir" "`cr 33 432 $this`"
+                error "`cr 32 432 $this`" "Can't extract $Archive"
+            expect_dir "$Source_Dir" "`cr 33 433 $this`"
         }
         tar cf - -C "Build_Parent_Dir" "$Source_Name" | tar xf - -C "$Build_Dir"
         chown -R "$Build_Acct:$Build_Group" "$Build_Dir"
         ;;
-        (*) error "`cr 34 437 $this`" "unimplemented pattern $Pattern" ;;
+        (*) error "`cr 34 438 $this`" "unimplemented pattern $Pattern" ;;
     esac
 }
 
@@ -472,6 +474,20 @@ log_error() {
     exit "$code"
 }
 
+# *** su commands
+
+# su_acct_dir_cmd [CONTEXT] account directory command...
+su_acct_dir_cmd() {
+    local cxt=''                # will grow
+    is_cs "$1" && { cxt="$1"; shift; }
+    local acct="$1" dir="$2" shift 2
+    # abuse our knowledge of ContextSeqence representation and watch out:
+    # - spaces or colons in the variables will produce a messy report!
+    cxt="$(cr acct = "$acct") $(cr dir = "$dir") $(cr shell = "$Build_Shell") $cxt"
+    log_report -command "$cxt" "$*"
+    su - "$acct" -s "$Build_Shell" -c "cd \"$dir\"; $*"
+}
+
 # *** Phase CONFIG
 
 do_config() {
@@ -480,7 +496,7 @@ do_config() {
     set_phase CONFIG
 
     declare -g Source_Root="$Build_Dir/$Source_Name"
-    expect_dir "$Source_Root" "`cr 35 483 $this`" Source_Root
+    expect_dir "$Source_Root" "`cr 35 498 $this`" Source_Root
 
     declare -g Config_Options=(
         --with-libxml
@@ -491,11 +507,11 @@ do_config() {
         "--prefix=$PG_Dir"
     )
 
-    $Verbose && report_param Config_Options
+    $Verbose && report_param_array Config_Options
 
-    log_report '-::' "$Source_Root ./configure" "${Config_Options[*]}"
-    su - "$Build_Acct" -s "$Build_Shell" -c "cd \"$Source_Root\"; ./configure ${Config_Options[*]}" |
-        log_example || log_error "`cr 36 498 $this`" "Build status $?"
+    local cxt="`cr 36 511 $this`"
+    su_acct_dir_cmd "$cxt" "$Build_Acct" "$Source_Root" ./configure "${Config_Options[*]}" |
+        log_example || log_error "$cxt" "./configure -> $?"
 }
 
 # *** Phases BUILD and INSTALL
@@ -505,8 +521,9 @@ do_build() {
 
     set_phase BUILD
 
-    su - "$Build_Acct" -s "$Build_Shell" -c "cd \"$Source_Root\"; make" |
-        log_example || log_error "`cr 37 509 $this`" "Build status $?"
+    local cxt="`cr 37 523 $this`"
+    su_acct_dir_cmd "$cxt" "$Build_Acct" "$Source_Root" make |
+        log_example || log_error "$cxt" "make -> $?"
 }
 
 do_install() {
@@ -514,8 +531,9 @@ do_install() {
 
     set_phase INSTALL
 
-    su - "$Build_Acct" -s "$Build_Shell" -c "cd \"$Source_Root\"; make install" |
-        log_example || log_error "`cr 38 518 $this`" "Build status $?"
+    local cxt="`cr 38 533 $this`"
+    su_acct_dir_cmd "$cxt" "$Build_Acct" "$Source_Root" make install |
+        log_example || log_error "$cxt" "make install -> $?"
 }
 
 # *** BUILD and INSTALL Some Contributed Modules
@@ -524,51 +542,60 @@ do_build_install_contribs() {
     local d this=do_build_install_contribs
 
     readonly Contrib_Dir="$Source_Root/contrib"
-    expect_dir "$Contrib_Dir" "`cr 39 527 $this`"
+    expect_dir "$Contrib_Dir" "`cr 39 544 $this`"
 
     for d in xml2 intarray citext hstore
     do
         set_phase $d-BUILD
-        su - "$Build_Acct" -s "$Build_Shell" -c "cd \"$Contrib_Dir\"; make" |
-            log_example || error "`cr 40 533 $this`" "Build status $?"
+        local cxt1="`cr 40 549 $this`"
+        su_acct_dir_cmd "$cxt1" "$Build_Acct" "$Contrib_Dir" make |
+            log_example || error "$cxt1" "make -> $?"
 
         set_phase $d-INSTALL
-        su - "$Build_Acct" -s "$Build_Shell" -c "cd \"$Contrib_Dir\"; make install" |
-            log_example || error "`cr 41 537 $this`" "Build status $?"
+        local cxt2="`cr 41 554 $this`"
+        su_acct_dir_cmd "$cxt2" "$Build_Acct" "$Contrib_Dir" make install |
+            log_example || error "$cxt2" "make install -> $?"
     done
 }
 
 # ** Setting Up Postgres
 # *** Procedures to run as Postgres
 
+# pg_cmd [CONTEXT] command...
 pg_cmd() {
-    log_report - "$*"
-    su - "$PG_Acct" -s "$Build_Shell" -c "cd \"$PG_Dir\"; bin/$*" | log_example
+    local cxt=''
+    is_cs "$1" && { cxt="$1"; shift; }
+    su_acct_dir_cmd "$cxt" "$PG_Acct" "$PG_Dir" "bin/$*" | log_example
 }
 
+# pg_data_cmd [CONTEXT] command...
 pg_data_cmd() {
+    local cxt=''
+    is_cs "$1" && { cxt="$1"; shift; }
     local cmd="$1"; shift
-    pg_cmd "$cmd" -D "$PG_Data" "$@"
+    pg_cmd "$cxt" "$cmd" -D "$PG_Data" "$@"
 }
 
+# try [CONTEXT] COMMAND...
 try() {
-    log_report -:: "$@"
-    local code="$1"; shift
-    "$@" | log_example || error "$code" "$Phase $1" "status $?"
+    local cxt=''
+    is_cs "$1" && { cxt="$1"; shift; }
+    log_report -command "$cxt" "$@"
+    "$@" | log_example || error "$cxt" "$Phase $1 -> $?"
 }
 
 # *** Initializing Postgres
 
 do_init_pg() {
     local this=do_init_pg
-    try !1 mkdir -p "$PG_Data"
-    try !1 empty_dir "$PG_Data"
-    try !1 chmod 700 "$PG_Data"
-    try !1 chown -R "$PG_Acct:$PG_Group" "$PG_Dir"
-    pg_data_cmd "`cr 42 568 $this`" initdb ||
-        error !1 initdb "status $?"
+    try "`cr 42 590 $this`" mkdir -p "$PG_Data"
+    try "`cr 43 591 $this`" empty_dir "$PG_Data"
+    try "`cr 44 592 $this`" chmod 700 "$PG_Data"
+    try "`cr 45 593 $this`" chown -R "$PG_Acct:$PG_Group" "$PG_Dir"
+    pg_data_cmd "`cr 46 594 $this`" initdb ||
+        error "`cr 47 595 $this` "initdb -> $?"
     # we should take care of this: !!
-    report "`cr 43 571 $this`" "-remember to" \
+    report "`cr 48 597 $this`" "-remember to" \
            "ln -s XFiles directory to $PG_Data"
 }
 
@@ -580,8 +607,8 @@ do_start_pg() {
     # and do something appropriate if there is!!
 
     # start the PostgreSQL server
-    pg_data_cmd 33! pg_ctl -l "$PG_Log" start ||
-        error "`cr 44 584 $this`" "starting server -> status $?"
+    pg_data_cmd "`cr 49 609 $this`" "pg_ctl -l "$PG_Log" start ||
+        error "`cr 50 610 $this`" "starting server -> $?"
     sleep 5	# seems to need a moment to get ready
 }
 
@@ -595,8 +622,8 @@ do_add_langs() {
     for lang in $langs; do
         # try $PG_Bin/createlang "$lang" template1
         printf "create trusted procedural language '%s';\n" "$lang" |
-            pg_cmd psql -a template1 || {
-            report "`cr 45 599 $this`" "createlang $lang -> status $?"
+            pg_cmd "`cr 51 624 $this`" psql -a template1 || {
+            report "`cr 52 625 $this`" "createlang $lang -> $?"
             let ++PG_Problem_Count
         }
     done
@@ -607,8 +634,8 @@ do_create_databases() {
     local db this=do_create_databases
     for db in wicci1
     do
-        pg_cmd createdb "$db" || {
-            report "`cr 46 611 $this`" "createdb $db -> status $?"
+        pg_cmd "`cr 53 636 $this`" createdb "$db" || {
+            report "`cr 54 637 $this`" "createdb $db -> $?"
             let ++PG_Problem_Count
         }
     done
@@ -616,12 +643,12 @@ do_create_databases() {
 
 do_manage_pg_config_file() {
     local this=do_manage_pg_config_file
-    pg_cmd mv "$PG_Conf" "$PG_Conf_Orig" ||
-        report "`cr 47 620 $this`" "${PG_Conf##*/} -> status $?"
-    pg_cmd cp "$PG_Conf_Orig" "$PG_Conf" ||
-        report "`cr 48 622 $this`" "${PG_Conf##*/} -> status $?"
+    pg_cmd "`cr 55 645 $this`" mv "$PG_Conf" "$PG_Conf_Orig" ||
+        log_report "`cr 56 646 $this`" "mv ${PG_Conf##*/} -> $?"
+    pg_cmd "`cr 57 647 $this`" cp "$PG_Conf_Orig" "$PG_Conf" ||
+        report "`cr 58 648 $this`" "cp ${PG_Conf##*/} -> $?"
     # we should take care of this: !!
-    report "`cr 49 624 $this`" '-remember to' \
+    report "`cr 59 650 $this`" '-remember to' \
            'add Make/wicci1 to dynamic_library_path'
     # and any other typical changes
 }
@@ -635,8 +662,8 @@ do_create_superusers() {
     echo -n 'Who should we make be PostgreSQL superuser(s)? '
     read users -r
     for user in $users; do
-        { user_exists "$user" && pg_cmd createuser --superuser "$user"; } ||
-                report "`cr 50 639 $this`" "createuser $user -> status $?"
+        { user_exists "$user" && pg_cmd "`cr 60 664 $this`" createuser --superuser "$user"; } ||
+                report "`cr 61 665 $this`" "createuser $user -> $?"
     done
 }
 
@@ -646,17 +673,24 @@ do_create_superusers() {
 
 do_suss_accounts
 do_suss_locations
-do_suss_build_dirs "$Version"
-do_suss_pg_dirs "$Version"
 
 do_suss_options "$@"
 set -- "${Pgm_Args[@]}"
-test root = "`whoami`" || error "`cr 51 654 "$Pgm_Name"`" "Must run as root!"
+test root = "`whoami`" || error "`cr 62 680 "$Pgm_Name"`" "Must run as root!"
 do_suss_args "$@"
+$Verbose && {
+    report "`cr 63 683`" "Arguments: ${Pgm_Args[*]}"
+    report "`cr 64 684`" "Initial Globals:\n"
+    report_params "${Initial_Globals[@]}"
+}
+
+do_suss_build_dirs "$Version"
+do_suss_pg_dirs "$Version"
 
 do_try_find_tcl
 do_prepare_build_dir
 do_config
+$Verbose && report_params "${Sussed_Globals[@]}"
 do_build
 do_install
 
